# This file is automatically generated, you probably don't want to edit this

SeminrPLSOptions <- if (requireNamespace("jmvcore", quietly = TRUE))
    R6::R6Class(
        "SeminrPLSOptions",
        inherit = jmvcore::Options,
        public = list(
            initialize = function(
                constructs = list(),
                paths = list(),
                innerWeights = "path_weighting",
                missing = "mean_replacement",
                bootstrap = FALSE,
                nboot = 1000L,
                seed = 123L,
                ...) {

                super$initialize(
                    package = "seminrjamovi",
                    name = "SeminrPLS",
                    requiresData = TRUE,
                    ...)

                private$..constructs <- jmvcore::OptionArray$new(
                    "constructs",
                    constructs,
                    template = jmvcore::OptionGroup$new(
                        "constructs",
                        list(
                            jmvcore::OptionString$new("name", default = ""),
                            jmvcore::OptionList$new(
                                "type",
                                options = list(
                                    list(name = "reflective",  title = "Reflective"),
                                    list(name = "composite_a", title = "Composite (Mode A)"),
                                    list(name = "composite_b", title = "Composite (Mode B)")
                                ),
                                default = "reflective"),
                            jmvcore::OptionVariables$new(
                                "indicators",
                                suggested = list("continuous", "ordinal"),
                                permitted = list("numeric", "factor"))
                        )))

                private$..paths <- jmvcore::OptionArray$new(
                    "paths",
                    paths,
                    template = jmvcore::OptionGroup$new(
                        "paths",
                        list(
                            jmvcore::OptionString$new("from", default = ""),
                            jmvcore::OptionString$new("to", default = "")
                        )))

                private$..innerWeights <- jmvcore::OptionList$new(
                    "innerWeights",
                    options = list(
                        list(name = "path_weighting",   title = "Path Weighting (Recommended)"),
                        list(name = "factor_weighting", title = "Factor Weighting")
                    ),
                    default = "path_weighting",
                    value = innerWeights)

                private$..missing <- jmvcore::OptionList$new(
                    "missing",
                    options = list(
                        list(name = "mean_replacement",  title = "Mean Replacement"),
                        list(name = "listwise_deletion", title = "Listwise Deletion")
                    ),
                    default = "mean_replacement",
                    value = missing)

                private$..bootstrap <- jmvcore::OptionBool$new(
                    "bootstrap",
                    default = FALSE,
                    value = bootstrap)

                private$..nboot <- jmvcore::OptionInteger$new(
                    "nboot",
                    default = 1000L,
                    min = 100L,
                    max = 10000L,
                    value = nboot)

                private$..seed <- jmvcore::OptionInteger$new(
                    "seed",
                    default = 123L,
                    min = 1L,
                    max = 2147483647L,
                    value = seed)

                self$.addOption(private$..constructs)
                self$.addOption(private$..paths)
                self$.addOption(private$..innerWeights)
                self$.addOption(private$..missing)
                self$.addOption(private$..bootstrap)
                self$.addOption(private$..nboot)
                self$.addOption(private$..seed)
            }),
        active = list(
            constructs  = function() private$..constructs$value,
            paths       = function() private$..paths$value,
            innerWeights = function() private$..innerWeights$value,
            missing     = function() private$..missing$value,
            bootstrap   = function() private$..bootstrap$value,
            nboot       = function() private$..nboot$value,
            seed        = function() private$..seed$value
        ),
        private = list(
            ..constructs   = NA,
            ..paths        = NA,
            ..innerWeights = NA,
            ..missing      = NA,
            ..bootstrap    = NA,
            ..nboot        = NA,
            ..seed         = NA
        ))


SeminrPLSResults <- if (requireNamespace("jmvcore", quietly = TRUE))
    R6::R6Class(
        "SeminrPLSResults",
        inherit = jmvcore::Group,
        active = list(
            modelSpec   = function() private$.items[["modelSpec"]],
            measurement = function() private$.items[["measurement"]],
            structural  = function() private$.items[["structural"]],
            rSquared    = function() private$.items[["rSquared"]],
            modelFit    = function() private$.items[["modelFit"]]
        ),
        private = list(),
        public = list(
            initialize = function(options) {
                super$initialize(
                    options = options,
                    name = "",
                    title = "PLS-SEM")

                self$add(jmvcore::Html$new(
                    options = options,
                    name = "modelSpec",
                    title = "Model Specification",
                    visible = TRUE))

                self$add(jmvcore::Table$new(
                    options = options,
                    name = "measurement",
                    title = "Measurement Model",
                    rows = 0,
                    columns = list(
                        list(name = "construct",  title = "Construct",      type = "text"),
                        list(name = "indicator",  title = "Indicator",      type = "text"),
                        list(name = "type",       title = "Type",           type = "text"),
                        list(name = "loading",    title = "Loading/Weight", type = "number", format = "zto"),
                        list(name = "se",         title = "SE",             type = "number", format = "zto",      visible = "(bootstrap)"),
                        list(name = "tstat",      title = "t-stat",         type = "number", format = "zto",      visible = "(bootstrap)"),
                        list(name = "pvalue",     title = "p",              type = "number", format = "zto,pvalue", visible = "(bootstrap)")
                    )))

                self$add(jmvcore::Table$new(
                    options = options,
                    name = "structural",
                    title = "Structural Model",
                    rows = 0,
                    columns = list(
                        list(name = "from",     title = "From",     type = "text"),
                        list(name = "to",       title = "To",       type = "text"),
                        list(name = "estimate", title = "Estimate", type = "number", format = "zto"),
                        list(name = "se",       title = "SE",       type = "number", format = "zto",       visible = "(bootstrap)"),
                        list(name = "tstat",    title = "t-stat",   type = "number", format = "zto",       visible = "(bootstrap)"),
                        list(name = "pvalue",   title = "p",        type = "number", format = "zto,pvalue", visible = "(bootstrap)"),
                        list(name = "ci_lower", title = "2.5%",     type = "number", format = "zto",       visible = "(bootstrap)"),
                        list(name = "ci_upper", title = "97.5%",    type = "number", format = "zto",       visible = "(bootstrap)")
                    )))

                self$add(jmvcore::Table$new(
                    options = options,
                    name = "rSquared",
                    title = "R-Squared",
                    rows = 0,
                    columns = list(
                        list(name = "construct", title = "Construct",   type = "text"),
                        list(name = "rsq",       title = "R\u00b2",      type = "number", format = "zto"),
                        list(name = "rsq_adj",   title = "Adjusted R\u00b2", type = "number", format = "zto")
                    )))

                self$add(jmvcore::Table$new(
                    options = options,
                    name = "modelFit",
                    title = "Model Fit",
                    rows = 1,
                    columns = list(
                        list(name = "srmr",      title = "SRMR",      type = "number"),
                        list(name = "rms_theta", title = "RMS Theta", type = "number"),
                        list(name = "nfl",       title = "NFI",       type = "number")
                    )))
            }))


SeminrPLSBase <- if (requireNamespace("jmvcore", quietly = TRUE))
    R6::R6Class(
        "SeminrPLSBase",
        inherit = jmvcore::Analysis,
        public = list(
            # options must be a SeminrPLSOptions object
            initialize = function(options, data = NULL, datasetId = "",
                                  analysisId = "", revision = 0) {
                super$initialize(
                    package    = "seminrjamovi",
                    name       = "SeminrPLS",
                    version    = c(0, 1, 0),
                    options    = options,
                    results    = SeminrPLSResults$new(options = options),
                    data       = data,
                    datasetId  = datasetId,
                    analysisId = analysisId,
                    revision   = revision)
            }))
